In [1]:
#Import Libraries

import pandas as pd
import numpy as np
import os

In [2]:
#Load Data
file_path = "E:\\f\\Portfolio Projects\\1\\Data-Job-Market-Intelligence\\data\\salaries.csv"
df = pd.read_csv(file_path)
print(f"Data loaded: {df.shape[0]} rows, {df.shape[1]} columns")

Data loaded: 105434 rows, 11 columns

In [3]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,EN,FT,Data Analist,65664,EUR,69120,NL,0,NL,M
1,2025,EN,FT,Data Analist,47652,EUR,50160,NL,0,NL,M
2,2025,EN,FT,Data Engineer,158113,USD,158113,US,0,US,M
3,2025,EN,FT,Data Engineer,87795,USD,87795,US,0,US,M
4,2025,EX,FT,Data Engineer,351410,USD,351410,US,0,US,M

In [4]:
df.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
105429,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
105430,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
105431,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
105432,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
105433,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L

In [5]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [6]:
df.dtypes

work_year             int64
experience_level        str
employment_type         str
job_title               str
salary                int64
salary_currency         str
salary_in_usd         int64
employee_residence      str
remote_ratio          int64
company_location        str
company_size            str
dtype: object

In [7]:
#Filter for entry-level friendly roles
#EN = Entry, MI = Mid-level
entry_level_mask = df['experience_level'].isin(['EN', 'MI'])
df_entry = df[entry_level_mask].copy()

print(f"Original: {len(df)} rows")
print(f"Entry/Mid friendly: {len(df_entry)} rows")

Original: 105434 rows
Entry/Mid friendly: 41740 rows

In [10]:
df_clean = df_entry[df_entry['salary_in_usd'].notna()].copy()

In [11]:
output_path = "E:\\f\\Portfolio Projects\\1\\Data-Job-Market-Intelligence\\data\\salaries_cleaned.csv"
df_clean.to_csv(output_path, index=False)
print(f"Cleaned data saved to {output_path}")
print(f"Shape: {df_clean.shape}")

Cleaned data saved to E:\f\Portfolio Projects\1\Data-Job-Market-Intelligence\data\salaries_cleaned.csv
Shape: (41740, 11)